# Generated by Django 5.1.6 on 2025-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapp',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='optional affiliate tracking link', null=True),
        ),
        migrations.AddField(
            model_name='travelapp',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Show this app as sponsored'),
        ),
    ]
