# Generated by Django 5.1.6 on 2025-06-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_emergencycontact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travelapp',
            unique_together={('name', 'country')},
        ),
    ]
