# Generated by Django 5.1.6 on 2025-06-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_travelapp_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelapp',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
