# Generated by Django 5.1.6 on 2025-06-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_alter_travelapp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=200)),
                ('translation', models.CharField(blank=True, max_length=200)),
                ('context_note', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='country.country')),
            ],
        ),
        migrations.CreateModel(
            name='UsefulTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='country.country')),
            ],
        ),
    ]
