# Generated by Django 5.1.6 on 2025-06-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_localphrase_usefultip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelapp',
            name='android_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travelapp',
            name='ios_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travelapp',
            name='website_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
