# Generated by Django 6.0.5 on 2026-05-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_countryvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('esim', 'eSIM & Connectivity'), ('insurance', 'Travel Insurance'), ('booking', 'Booking Platforms'), ('utilities', 'Other Useful Services')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('price_from', models.CharField(blank=True, default='', max_length=120)),
                ('coverage', models.CharField(blank=True, default='', max_length=255)),
                ('support', models.CharField(blank=True, default='', max_length=120)),
                ('refund', models.CharField(blank=True, default='', max_length=120)),
                ('site', models.URLField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='country.country')),
            ],
            options={
                'ordering': ('country__name', 'section', '-is_featured', 'name'),
                'unique_together': {('country', 'section', 'name')},
            },
        ),
    ]