# Generated by Django 5.1.6 on 2026-04-17 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0008_origincountryassistance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOriginPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_origin_preferences', to='country.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
